### ISSUE TITLE
Broken for webp files?

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/PyQC#11]
```
PyQC.py *webp
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/gdevenyi/projects/PyQC/PyQC.py", line 274, in <module>
    form = MainWindow()
  File "/home/gdevenyi/projects/PyQC/PyQC.py", line 47, in __init__
    self.openArgumentFiles()
  File "/home/gdevenyi/projects/PyQC/PyQC.py", line 205, in openArgumentFiles
    self.label.load(self.filelist[self.listlocation])
  File "/home/gdevenyi/projects/PyQC/image_widget.py", line 153, in load
    self.content.adaptScale(size)
  File "/home/gdevenyi/projects/PyQC/image_widget.py", line 52, in adaptScale
    n_size = QSize(width, size.height())
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'
```

**Comment by gdevenyi** [comment]
Version:
```
ii  python3-pyqt5                                 5.15.6+dfsg-1ubuntu3                        amd64        Python 3 bindings for Qt5

```
